### ISSUE TITLE
error on figure 3.12

### ISSUE THREAD

**Issue by MAKIO135** [nature-of-code/book-website-2nd-edition#38]
![Figure 3.12](http://natureofcode.com/book/imgs/chapter03/ch03_12.png)
The formula _sin(θ) = Fg/Fp_ should be _sin(θ) = Fp/Fg_

**Comment by shiffman** [comment]
It is fixed!

![image](https://user-images.githubusercontent.com/191758/213203337-16c2f3b8-f337-4e5a-8091-182371e219a6.png)

**Comment by MAKIO135** [comment]
✨
