### ISSUE TITLE
figure 1.7

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/book-website-2nd-edition#48]
https://github.com/shiffman/The-Nature-of-Code-archive/issues/301
- -2, 2 are swapped in vector length labels
- -v should be labeled in last diagram

**Comment by shiffman** [comment]
@jasongao97 this would be a good issue to test the new workflow of fixing an image in notion and having it populate to the github repo? Or am I supposed to upload the image to the repo and then update it in Notion? I don't remember!

**Comment by shiffman** [comment]
@zee-em I noticed we lost the `2` and `-2` labels on the far right vector? I think those are helpful to include.

![image](https://user-images.githubusercontent.com/191758/213203149-e6fcfaa8-4a03-4047-9f03-93fb5a98a024.png)

I'm also now wondering if we should show a light grey vector as the result of the subtraction (see red one above) and even if the dotted lines in that 3rd diagram should be removed?

**Comment by shiffman** [comment]
note: change dotted lines to gray rather than remove

**Comment by shiffman** [comment]
also switch the -2 and 2 dotted lines to the other side of the arrow on the far right

**Comment by zee-em** [comment]
updated and uploaded.
